import {
  Appointment,
  CustomerBirthday,
  DailySalesData,
  InventoryItem,
  NotificationItem,
  PaymentBreakdownData,
  ServiceData,
  Stylist,
  Transaction,
} from '../types';

export const INITIAL_DAILY_SALES: DailySalesData[] = [
  { day: 'Monday', sales: 14200, appointments: 18, target: 15000 },
  { day: 'Tuesday', sales: 16800, appointments: 21, target: 15000 },
  { day: 'Wednesday', sales: 15400, appointments: 19, target: 15000 },
  { day: 'Thursday', sales: 18900, appointments: 24, target: 16000 },
  { day: 'Friday', sales: 22100, appointments: 28, target: 18000 },
  { day: 'Saturday', sales: 28500, appointments: 36, target: 22000 },
  { day: 'Sunday', sales: 24300, appointments: 31, target: 20000 },
];

export const INITIAL_PAYMENT_BREAKDOWN: PaymentBreakdownData[] = [
  { name: 'UPI', value: 8343, percentage: 45, color: '#6A3F4D' },
  { name: 'Cash', value: 6489, percentage: 35, color: '#A8828F' },
  { name: 'Card', value: 2781, percentage: 15, color: '#8E7B82' },
  { name: 'Split', value: 927, percentage: 5, color: '#EBD9DF' },
];

export const INITIAL_TOP_SERVICES: ServiceData[] = [
  { serviceName: 'Hair Cut & Styling', bookings: 48, revenue: 28800 },
  { serviceName: 'Hair Spa & Keratin', bookings: 32, revenue: 48000 },
  { serviceName: 'Hydra Facial', bookings: 26, revenue: 39000 },
  { serviceName: 'Balayage / Hair Color', bookings: 22, revenue: 55000 },
  { serviceName: 'Bridal Makeup', bookings: 12, revenue: 84000 },
  { serviceName: 'Waxing & Pedicure', bookings: 38, revenue: 19000 },
];

export const INITIAL_STYLISTS: Stylist[] = [
  {
    id: 's1',
    name: 'Aarav Kapoor',
    roleTitle: 'Master Senior Stylist',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    todayRevenue: 6450,
    appointmentsCount: 7,
    commissionRate: 15,
    commissionAmount: 967,
    rating: 4.9,
  },
  {
    id: 's2',
    name: 'Meera Rajput',
    roleTitle: 'Senior Colorist & Spa Expert',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    todayRevenue: 5200,
    appointmentsCount: 6,
    commissionRate: 15,
    commissionAmount: 780,
    rating: 4.8,
  },
  {
    id: 's3',
    name: 'Rohan Verma',
    roleTitle: 'Grooming & Barber Lead',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    todayRevenue: 3890,
    appointmentsCount: 5,
    commissionRate: 12,
    commissionAmount: 466,
    rating: 4.9,
  },
  {
    id: 's4',
    name: 'Ananya Deshmukh',
    roleTitle: 'Aesthetician & Makeup Artist',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    todayRevenue: 2200,
    appointmentsCount: 4,
    commissionRate: 12,
    commissionAmount: 264,
    rating: 4.7,
  },
  {
    id: 's5',
    name: 'Karan Malhotra',
    roleTitle: 'Hair Specialist',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    todayRevenue: 1800,
    appointmentsCount: 4,
    commissionRate: 10,
    commissionAmount: 180,
    rating: 4.6,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-101',
    invoiceNo: 'INV-2026-0891',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98765 43210',
    stylistName: 'Aarav Kapoor',
    services: ['Hair Cut', 'Blow Dry'],
    amount: 1450,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '10:15 AM',
    date: 'Today',
  },
  {
    id: 'tx-102',
    invoiceNo: 'INV-2026-0892',
    customerName: 'Rajesh Mehta',
    customerPhone: '+91 98123 45678',
    stylistName: 'Rohan Verma',
    services: ['Beard Trim', 'Head Massage'],
    amount: 850,
    paymentMethod: 'Cash',
    status: 'Paid',
    time: '10:45 AM',
    date: 'Today',
  },
  {
    id: 'tx-103',
    invoiceNo: 'INV-2026-0893',
    customerName: 'Sanya Gupta',
    customerPhone: '+91 99887 76655',
    stylistName: 'Meera Rajput',
    services: ['Global Hair Color', 'Olaplex'],
    amount: 4800,
    paymentMethod: 'Card',
    status: 'Paid',
    time: '11:20 AM',
    date: 'Today',
  },
  {
    id: 'tx-104',
    invoiceNo: 'INV-2026-0894',
    customerName: 'Anik Roy',
    customerPhone: '+91 97654 32109',
    stylistName: 'Karan Malhotra',
    services: ['Men Styling', 'Face Cleanup'],
    amount: 1200,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '11:50 AM',
    date: 'Today',
  },
  {
    id: 'tx-105',
    invoiceNo: 'INV-2026-0895',
    customerName: 'Dr. Sunita Rao',
    customerPhone: '+91 98220 11223',
    stylistName: 'Ananya Deshmukh',
    services: ['Hydra Facial', 'Eyebrow Threading'],
    amount: 2600,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '12:30 PM',
    date: 'Today',
  },
  {
    id: 'tx-106',
    invoiceNo: 'INV-2026-0896',
    customerName: 'Vikram Sethi',
    customerPhone: '+91 99001 22334',
    stylistName: 'Aarav Kapoor',
    services: ['Hair Wash', 'Groom Haircut'],
    amount: 1100,
    paymentMethod: 'Cash',
    status: 'Paid',
    time: '01:10 PM',
    date: 'Today',
  },
  {
    id: 'tx-107',
    invoiceNo: 'INV-2026-0897',
    customerName: 'Neha Nair',
    customerPhone: '+91 98450 66778',
    stylistName: 'Meera Rajput',
    services: ['Keratin Treatment'],
    amount: 5500,
    paymentMethod: 'Split',
    status: 'Paid',
    time: '01:45 PM',
    date: 'Today',
  },
  {
    id: 'tx-108',
    invoiceNo: 'INV-2026-0898',
    customerName: 'Rahul Joshi',
    customerPhone: '+91 97112 33445',
    stylistName: 'Rohan Verma',
    services: ['Royal Shave', 'Facial Scrub'],
    amount: 950,
    paymentMethod: 'UPI',
    status: 'Pending',
    time: '02:15 PM',
    date: 'Today',
  },
  {
    id: 'tx-109',
    invoiceNo: 'INV-2026-0899',
    customerName: 'Kavita Menon',
    customerPhone: '+91 98990 11223',
    stylistName: 'Ananya Deshmukh',
    services: ['Pedicure Spa', 'Manicure'],
    amount: 1800,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '02:50 PM',
    date: 'Today',
  },
  {
    id: 'tx-110',
    invoiceNo: 'INV-2026-0900',
    customerName: 'Arjun Bansal',
    customerPhone: '+91 96543 21098',
    stylistName: 'Karan Malhotra',
    services: ['Men Haircut'],
    amount: 600,
    paymentMethod: 'Cash',
    status: 'Refunded',
    time: '03:10 PM',
    date: 'Today',
  },
  {
    id: 'tx-111',
    invoiceNo: 'INV-2026-0901',
    customerName: 'Divya Chawla',
    customerPhone: '+91 98711 22334',
    stylistName: 'Aarav Kapoor',
    services: ['Hair Spa', 'Serum Polish'],
    amount: 2100,
    paymentMethod: 'Card',
    status: 'Paid',
    time: '03:40 PM',
    date: 'Today',
  },
  {
    id: 'tx-112',
    invoiceNo: 'INV-2026-0902',
    customerName: 'Aman Deep',
    customerPhone: '+91 98112 44556',
    stylistName: 'Rohan Verma',
    services: ['Beard Spa & Haircut'],
    amount: 1250,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '04:05 PM',
    date: 'Today',
  },
  {
    id: 'tx-113',
    invoiceNo: 'INV-2026-0903',
    customerName: 'Simran Bajaj',
    customerPhone: '+91 99554 33221',
    stylistName: 'Meera Rajput',
    services: ['Balayage Touch Up'],
    amount: 3200,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '04:30 PM',
    date: 'Today',
  },
  {
    id: 'tx-114',
    invoiceNo: 'INV-2026-0904',
    customerName: 'Gaurav Khanna',
    customerPhone: '+91 98887 66554',
    stylistName: 'Karan Malhotra',
    services: ['Scalp Treatment'],
    amount: 1500,
    paymentMethod: 'Cash',
    status: 'Paid',
    time: '05:00 PM',
    date: 'Today',
  },
  {
    id: 'tx-115',
    invoiceNo: 'INV-2026-0905',
    customerName: 'Meenal Reddy',
    customerPhone: '+91 97776 55443',
    stylistName: 'Ananya Deshmukh',
    services: ['Gold Glow Facial'],
    amount: 2800,
    paymentMethod: 'Card',
    status: 'Paid',
    time: '05:25 PM',
    date: 'Today',
  },
  // Previous transactions sample
  {
    id: 'tx-116',
    invoiceNo: 'INV-2026-0890',
    customerName: 'Ritu Varma',
    customerPhone: '+91 98333 22110',
    stylistName: 'Aarav Kapoor',
    services: ['Hair Trim & Wash'],
    amount: 900,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '07:10 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-117',
    invoiceNo: 'INV-2026-0889',
    customerName: 'Siddharth Saxena',
    customerPhone: '+91 98221 00998',
    stylistName: 'Rohan Verma',
    services: ['Detan Pack', 'Haircut'],
    amount: 1300,
    paymentMethod: 'Cash',
    status: 'Paid',
    time: '06:45 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-118',
    invoiceNo: 'INV-2026-0888',
    customerName: 'Isha Patel',
    customerPhone: '+91 99112 88776',
    stylistName: 'Meera Rajput',
    services: ['Bridal Trial Hair'],
    amount: 3500,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '06:15 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-119',
    invoiceNo: 'INV-2026-0887',
    customerName: 'Tarun Gill',
    customerPhone: '+91 98444 33221',
    stylistName: 'Karan Malhotra',
    services: ['Hair Coloring Black'],
    amount: 1600,
    paymentMethod: 'Cash',
    status: 'Pending',
    time: '05:30 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-120',
    invoiceNo: 'INV-2026-0886',
    customerName: 'Preeti Bhatia',
    customerPhone: '+91 98555 44332',
    stylistName: 'Ananya Deshmukh',
    services: ['Waxing Full Legs'],
    amount: 1200,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '05:00 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-121',
    invoiceNo: 'INV-2026-0885',
    customerName: 'Manish Pandey',
    customerPhone: '+91 98666 55443',
    stylistName: 'Rohan Verma',
    services: ['Executive Haircut'],
    amount: 800,
    paymentMethod: 'Cash',
    status: 'Paid',
    time: '04:15 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-122',
    invoiceNo: 'INV-2026-0884',
    customerName: 'Shalini Ahuja',
    customerPhone: '+91 98777 66554',
    stylistName: 'Meera Rajput',
    services: ['Hair Smoothing Touchup'],
    amount: 4000,
    paymentMethod: 'Card',
    status: 'Paid',
    time: '03:30 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-123',
    invoiceNo: 'INV-2026-0883',
    customerName: 'Varun Grover',
    customerPhone: '+91 98888 77665',
    stylistName: 'Aarav Kapoor',
    services: ['Beard Styling & Oil Massage'],
    amount: 950,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '02:45 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-124',
    invoiceNo: 'INV-2026-0882',
    customerName: 'Tanvi Shah',
    customerPhone: '+91 98999 88776',
    stylistName: 'Ananya Deshmukh',
    services: ['O3+ Facial'],
    amount: 2500,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '02:00 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-125',
    invoiceNo: 'INV-2026-0881',
    customerName: 'Hardik Trivedi',
    customerPhone: '+91 99000 99887',
    stylistName: 'Karan Malhotra',
    services: ['Hair Wash & Blow Dry'],
    amount: 500,
    paymentMethod: 'Cash',
    status: 'Paid',
    time: '01:15 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-126',
    invoiceNo: 'INV-2026-0880',
    customerName: 'Nisha Singhal',
    customerPhone: '+91 99111 00112',
    stylistName: 'Meera Rajput',
    services: ['Hair Highlights Foil'],
    amount: 3800,
    paymentMethod: 'Split',
    status: 'Paid',
    time: '12:30 PM',
    date: 'Yesterday',
  },
  {
    id: 'tx-127',
    invoiceNo: 'INV-2026-0879',
    customerName: 'Chirag Chadha',
    customerPhone: '+91 99222 11223',
    stylistName: 'Rohan Verma',
    services: ['Head Massage Spa'],
    amount: 750,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '11:45 AM',
    date: 'Yesterday',
  },
  {
    id: 'tx-128',
    invoiceNo: 'INV-2026-0878',
    customerName: 'Anusha Iyer',
    customerPhone: '+91 99333 22334',
    stylistName: 'Ananya Deshmukh',
    services: ['Nail Art & Gel Extensions'],
    amount: 2200,
    paymentMethod: 'Card',
    status: 'Paid',
    time: '11:00 AM',
    date: 'Yesterday',
  },
  {
    id: 'tx-129',
    invoiceNo: 'INV-2026-0877',
    customerName: 'Kunal Kapoor',
    customerPhone: '+91 99444 33445',
    stylistName: 'Aarav Kapoor',
    services: ['Hair Cut & Beard Combo'],
    amount: 1200,
    paymentMethod: 'UPI',
    status: 'Paid',
    time: '10:30 AM',
    date: 'Yesterday',
  },
  {
    id: 'tx-130',
    invoiceNo: 'INV-2026-0876',
    customerName: 'Smriti Sen',
    customerPhone: '+91 99555 44556',
    stylistName: 'Meera Rajput',
    services: ['Deep Conditioning Mask'],
    amount: 1400,
    paymentMethod: 'Cash',
    status: 'Refunded',
    time: '10:00 AM',
    date: 'Yesterday',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    time: '10:00 AM',
    customerName: 'Ananya Sharma',
    customerPhone: '+91 98765 11111',
    stylistName: 'Meera Rajput',
    service: 'Hair Spa & Scalp Massage',
    amount: 1800,
    status: 'Completed',
    notes: 'Allergic to ammonia products',
  },
  {
    id: 'apt-2',
    time: '10:30 AM',
    customerName: 'Vikramaditya Roy',
    customerPhone: '+91 98765 22222',
    stylistName: 'Rohan Verma',
    service: 'Executive Haircut & Shave',
    amount: 1100,
    status: 'Completed',
  },
  {
    id: 'apt-3',
    time: '11:15 AM',
    customerName: 'Sneha Kulkarni',
    customerPhone: '+91 98765 33333',
    stylistName: 'Aarav Kapoor',
    service: 'Layered Haircut & Blowdry',
    amount: 1600,
    status: 'Checked In',
    notes: 'Requested warm tea',
  },
  {
    id: 'apt-4',
    time: '11:45 AM',
    customerName: 'Deepak Merchant',
    customerPhone: '+91 98765 44444',
    stylistName: 'Karan Malhotra',
    service: 'Hair Color Touchup',
    amount: 1500,
    status: 'Checked In',
  },
  {
    id: 'apt-5',
    time: '12:30 PM',
    customerName: 'Pooja Hegde',
    customerPhone: '+91 98765 55555',
    stylistName: 'Ananya Deshmukh',
    service: 'Hydra Glow Facial',
    amount: 3000,
    status: 'Booked',
    notes: 'VIP Customer',
  },
  {
    id: 'apt-6',
    time: '01:15 PM',
    customerName: 'Harsh Vardhan',
    customerPhone: '+91 98765 66666',
    stylistName: 'Rohan Verma',
    service: 'Beard Grooming & Styling',
    amount: 750,
    status: 'Booked',
  },
  {
    id: 'apt-7',
    time: '02:00 PM',
    customerName: 'Rashmi Sawant',
    customerPhone: '+91 98765 77777',
    stylistName: 'Meera Rajput',
    service: 'Balayage & Hair Gloss',
    amount: 4500,
    status: 'Booked',
  },
  {
    id: 'apt-8',
    time: '02:45 PM',
    customerName: 'Arnav Nambiar',
    customerPhone: '+91 98765 88888',
    stylistName: 'Aarav Kapoor',
    service: 'Grooming Combo',
    amount: 1400,
    status: 'Booked',
  },
  {
    id: 'apt-9',
    time: '03:30 PM',
    customerName: 'Bhavna Doshi',
    customerPhone: '+91 98765 99999',
    stylistName: 'Ananya Deshmukh',
    service: 'Pedicure & Manicure Spa',
    amount: 1900,
    status: 'Booked',
  },
  {
    id: 'apt-10',
    time: '04:15 PM',
    customerName: 'Yash Saxena',
    customerPhone: '+91 98765 00000',
    stylistName: 'Karan Malhotra',
    service: 'Men Styling & Wash',
    amount: 650,
    status: 'Booked',
  },
  {
    id: 'apt-11',
    time: '05:00 PM',
    customerName: 'Natasha Wadia',
    customerPhone: '+91 98711 11111',
    stylistName: 'Meera Rajput',
    service: 'Global Hair Coloring',
    amount: 4000,
    status: 'Booked',
  },
  {
    id: 'apt-12',
    time: '05:45 PM',
    customerName: 'Karan Johar',
    customerPhone: '+91 98722 22222',
    stylistName: 'Rohan Verma',
    service: 'Detan & Face Scrub',
    amount: 950,
    status: 'Booked',
  },
  {
    id: 'apt-13',
    time: '06:30 PM',
    customerName: 'Dr. Monika Shah',
    customerPhone: '+91 98733 33333',
    stylistName: 'Aarav Kapoor',
    service: 'Hair Straightening Touchup',
    amount: 3500,
    status: 'Booked',
  },
  {
    id: 'apt-14',
    time: '07:15 PM',
    customerName: 'Samir Alvi',
    customerPhone: '+91 98744 44444',
    stylistName: 'Karan Malhotra',
    service: 'Haircut & Head Massage',
    amount: 900,
    status: 'Cancelled',
    notes: 'Rescheduled for tomorrow',
  },
  {
    id: 'apt-15',
    time: '08:00 PM',
    customerName: 'Richa Chaddha',
    customerPhone: '+91 98755 55555',
    stylistName: 'Ananya Deshmukh',
    service: 'Party Makeup & Hair',
    amount: 3200,
    status: 'Booked',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    itemName: 'Hair Color Black No. 1 (L’Oréal)',
    category: 'Hair Care',
    remainingQty: 3,
    minQty: 10,
    unit: 'Tubes',
    status: 'Low',
    supplier: 'BeautySupplies Co.',
    unitPrice: 450,
  },
  {
    id: 'inv-2',
    itemName: 'Organic Wax Beans (Honey Gold)',
    category: 'Skin Care',
    remainingQty: 5,
    minQty: 20,
    unit: 'Kg',
    status: 'Critical',
    supplier: 'SatinSmooth India',
    unitPrice: 650,
  },
  {
    id: 'inv-3',
    itemName: 'Keratin Nourishing Shampoo 1000ml',
    category: 'Hair Care',
    remainingQty: 7,
    minQty: 15,
    unit: 'Bottles',
    status: 'Low',
    supplier: 'Schwarzkopf Professional',
    unitPrice: 1200,
  },
  {
    id: 'inv-4',
    itemName: 'Argan Oil Smoothing Serum 100ml',
    category: 'Hair Treatment',
    remainingQty: 2,
    minQty: 8,
    unit: 'Bottles',
    status: 'Critical',
    supplier: 'Moroccanoil Direct',
    unitPrice: 1800,
  },
  {
    id: 'inv-5',
    itemName: 'Hydra Facial Serum Set (A+B)',
    category: 'Aesthetics',
    remainingQty: 4,
    minQty: 12,
    unit: 'Kits',
    status: 'Low',
    supplier: 'GlowSkin Tech',
    unitPrice: 3200,
  },
  {
    id: 'inv-6',
    itemName: 'Disposable Towels (Pack of 100)',
    category: 'Consumables',
    remainingQty: 6,
    minQty: 15,
    unit: 'Packs',
    status: 'Low',
    supplier: 'HygienePro Essentials',
    unitPrice: 350,
  },
  {
    id: 'inv-7',
    itemName: 'Bleach Powder Blue 500g',
    category: 'Hair Color',
    remainingQty: 3,
    minQty: 10,
    unit: 'Tubs',
    status: 'Low',
    supplier: 'BeautySupplies Co.',
    unitPrice: 850,
  },
  {
    id: 'inv-8',
    itemName: 'Styling Gel Ultra Hold 500ml',
    category: 'Grooming',
    remainingQty: 4,
    minQty: 10,
    unit: 'Tubs',
    status: 'Low',
    supplier: 'TIGI Bedhead India',
    unitPrice: 920,
  },
  {
    id: 'inv-9',
    itemName: 'Pedicure Salt Scrub Lavender 1kg',
    category: 'Spa Care',
    remainingQty: 12,
    minQty: 10,
    unit: 'Jars',
    status: 'Optimal',
    supplier: 'NatureSpa Organics',
    unitPrice: 550,
  },
  {
    id: 'inv-10',
    itemName: 'Facial Cleansing Sponges (50s)',
    category: 'Aesthetics',
    remainingQty: 18,
    minQty: 10,
    unit: 'Packs',
    status: 'Optimal',
    supplier: 'GlowSkin Tech',
    unitPrice: 200,
  },
];

export const INITIAL_BIRTHDAYS: CustomerBirthday[] = [
  {
    id: 'b1',
    name: 'Ananya Sharma',
    phone: '+91 98765 11111',
    age: 28,
    birthDate: 'Today',
    isToday: true,
    preferredServices: ['Hair Spa', 'Hydra Facial'],
  },
  {
    id: 'b2',
    name: 'Devina Oberoi',
    phone: '+91 99887 11223',
    age: 32,
    birthDate: 'Today',
    isToday: true,
    preferredServices: ['Bridal Makeup', 'Balayage'],
  },
  {
    id: 'b3',
    name: 'Rohan Mehra',
    phone: '+91 98112 33445',
    age: 25,
    birthDate: 'Aug 8 (Tomorrow)',
    isToday: false,
    preferredServices: ['Executive Shave', 'Beard Trim'],
  },
  {
    id: 'b4',
    name: 'Tanya Kashyap',
    phone: '+91 97654 00112',
    age: 30,
    birthDate: 'Aug 10',
    isToday: false,
    preferredServices: ['Nail Art', 'Gold Facial'],
  },
  {
    id: 'b5',
    name: 'Karan Malhotra',
    phone: '+91 98990 44556',
    age: 29,
    birthDate: 'Aug 12',
    isToday: false,
    preferredServices: ['Men Styling', 'Scalp Spa'],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    title: 'Upcoming Appointment',
    message: 'Ananya Sharma (Hair Spa) is scheduled in 15 minutes with Meera Rajput.',
    time: '10 mins ago',
    read: false,
    category: 'appointment',
    priority: 'high',
  },
  {
    id: 'n2',
    title: 'Low Stock Alert',
    message: 'Wax Beans & Hair Color Black reached critical threshold (≤ 5 units).',
    time: '25 mins ago',
    read: false,
    category: 'inventory',
    priority: 'high',
  },
  {
    id: 'n3',
    title: 'Sales Target Milestone',
    message: 'Congratulations! Today’s sales reached ₹18,540 (103% of target).',
    time: '1 hour ago',
    read: false,
    category: 'sales',
    priority: 'medium',
  },
  {
    id: 'n4',
    title: 'New Customer Registered',
    message: 'Rahul Verma signed up via QR Walk-in and booked a Beard Grooming session.',
    time: '2 hours ago',
    read: true,
    category: 'customer',
    priority: 'low',
  },
  {
    id: 'n5',
    title: 'Birthday Reminder',
    message: '2 active customers have birthdays today! Send 20% OFF discount coupon.',
    time: '3 hours ago',
    read: true,
    category: 'customer',
    priority: 'medium',
  },
];
