import { Employee, RoleDefinition } from '../types/employee';

export const INITIAL_ROLES: RoleDefinition[] = [
  {
    id: 'role-1',
    title: 'Master Senior Stylist',
    department: 'Hair Care',
    description: 'Expert in creative precision cuts, couture styling, and client consultation.',
    defaultCommissionRate: 15,
    permissions: ['POS Billing', 'Appointments Booking', 'Custom Services', 'Reports View'],
    color: '#6A3F4D',
  },
  {
    id: 'role-2',
    title: 'Senior Colorist & Spa Expert',
    department: 'Hair Care',
    description: 'Specialist in balayage, highlight technique, keratin, and scalp spa treatments.',
    defaultCommissionRate: 15,
    permissions: ['POS Billing', 'Appointments Booking', 'Inventory Usage Log'],
    color: '#8E7B82',
  },
  {
    id: 'role-3',
    title: 'Grooming & Barber Lead',
    department: 'Grooming & Barber',
    description: 'Head of men’s beard styling, royal hot-towel shaves, and executive cuts.',
    defaultCommissionRate: 12,
    permissions: ['POS Billing', 'Appointments Booking', 'Walk-in Queue'],
    color: '#6E5C63',
  },
  {
    id: 'role-4',
    title: 'Aesthetician & Makeup Artist',
    department: 'Skin & Aesthetics',
    description: 'Certified hydra-facial practitioner, party makeup, and skincare expert.',
    defaultCommissionRate: 12,
    permissions: ['POS Billing', 'Appointments Booking', 'Skincare Log'],
    color: '#A8828F',
  },
  {
    id: 'role-5',
    title: 'Hair Specialist',
    department: 'Hair Care',
    description: 'General hair care, washes, deep conditioning, and blow-dry styling.',
    defaultCommissionRate: 10,
    permissions: ['Appointments View', 'Inventory Usage Log'],
    color: '#8E7B82',
  },
  {
    id: 'role-6',
    title: 'Salon Manager',
    department: 'Management',
    description: 'Oversees daily salon operations, payroll, inventory, staff shifts, and POS.',
    defaultCommissionRate: 18,
    permissions: ['Full Access', 'Commission Edit', 'Shift Roster Manager', 'Financial Reports'],
    color: '#2D1F24',
  },
  {
    id: 'role-7',
    title: 'Front Desk Executive',
    department: 'Front Desk',
    description: 'Manages client check-ins, appointment scheduling, billing, and phone queries.',
    defaultCommissionRate: 5,
    permissions: ['POS Billing', 'Appointments Booking', 'Customer Database', 'Register Cash'],
    color: '#6E5C63',
  },
];

export const DEFAULT_WEEKLY_SHIFTS = [
  { day: 'Mon' as const, shiftType: 'Morning' as const, startTime: '09:00 AM', endTime: '04:00 PM' },
  { day: 'Tue' as const, shiftType: 'Morning' as const, startTime: '09:00 AM', endTime: '04:00 PM' },
  { day: 'Wed' as const, shiftType: 'Evening' as const, startTime: '01:00 PM', endTime: '08:00 PM' },
  { day: 'Thu' as const, shiftType: 'Full Day' as const, startTime: '09:30 AM', endTime: '07:30 PM' },
  { day: 'Fri' as const, shiftType: 'Full Day' as const, startTime: '09:30 AM', endTime: '07:30 PM' },
  { day: 'Sat' as const, shiftType: 'Full Day' as const, startTime: '09:00 AM', endTime: '08:00 PM' },
  { day: 'Sun' as const, shiftType: 'Off' as const, startTime: '-', endTime: '-' },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'Aarav Kapoor',
    roleTitle: 'Master Senior Stylist',
    department: 'Hair Care',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    email: 'aarav.kapoor@beigesalon.com',
    phone: '+91 98765 43210',
    startDate: '12 Jan 2022',
    status: 'On Shift',
    baseSalary: 45000,
    commissionRate: 15,
    commissionTiers: [
      { categoryName: 'Hair Cuts & Styling', ratePercentage: 15 },
      { categoryName: 'Hair Chemical Treatments', ratePercentage: 18 },
      { categoryName: 'Retail Products', ratePercentage: 10 },
    ],
    todaySales: 6450,
    monthlySales: 184500,
    commissionEarnedToday: 967,
    commissionEarnedMonth: 27675,
    tipsToday: 350,
    rating: 4.9,
    completedAppointmentsCount: 7,
    shifts: DEFAULT_WEEKLY_SHIFTS,
    emergencyContact: {
      name: 'Sunita Kapoor',
      relationship: 'Spouse',
      phone: '+91 98765 99887',
    },
    specialties: ['Couture Haircuts', 'Balayage Color', 'Keratin Smoothing', 'Beard Grooming'],
    bio: '10+ years of experience with celebrity hair styling and advanced hair restructuring.',
    payoutStatus: 'Paid',
  },
  {
    id: 'emp-2',
    name: 'Meera Rajput',
    roleTitle: 'Senior Colorist & Spa Expert',
    department: 'Hair Care',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    email: 'meera.rajput@beigesalon.com',
    phone: '+91 98123 45678',
    startDate: '05 Mar 2023',
    status: 'On Shift',
    baseSalary: 40000,
    commissionRate: 15,
    commissionTiers: [
      { categoryName: 'Hair Color & Balayage', ratePercentage: 16 },
      { categoryName: 'Scalp & Hair Spa', ratePercentage: 14 },
    ],
    todaySales: 5200,
    monthlySales: 162000,
    commissionEarnedToday: 780,
    commissionEarnedMonth: 24300,
    tipsToday: 280,
    rating: 4.8,
    completedAppointmentsCount: 6,
    shifts: [
      { day: 'Mon', shiftType: 'Full Day', startTime: '10:00 AM', endTime: '07:30 PM' },
      { day: 'Tue', shiftType: 'Full Day', startTime: '10:00 AM', endTime: '07:30 PM' },
      { day: 'Wed', shiftType: 'Morning', startTime: '09:00 AM', endTime: '04:00 PM' },
      { day: 'Thu', shiftType: 'Off', startTime: '-', endTime: '-' },
      { day: 'Fri', shiftType: 'Full Day', startTime: '10:00 AM', endTime: '08:00 PM' },
      { day: 'Sat', shiftType: 'Full Day', startTime: '09:30 AM', endTime: '08:30 PM' },
      { day: 'Sun', shiftType: 'Full Day', startTime: '10:00 AM', endTime: '06:00 PM' },
    ],
    emergencyContact: {
      name: 'Ramesh Rajput',
      relationship: 'Father',
      phone: '+91 98123 00112',
    },
    specialties: ['Olaplex Treatments', 'Pastel Coloring', 'Scalp Detox', 'Blowouts'],
    bio: 'Master Colorist certified by L’Oréal Academy with passion for healthy hair shine.',
    payoutStatus: 'Pending',
  },
  {
    id: 'emp-3',
    name: 'Rohan Verma',
    roleTitle: 'Grooming & Barber Lead',
    department: 'Grooming & Barber',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    email: 'rohan.verma@beigesalon.com',
    phone: '+91 99887 76655',
    startDate: '18 Aug 2022',
    status: 'On Shift',
    baseSalary: 38000,
    commissionRate: 12,
    commissionTiers: [
      { categoryName: 'Men Grooming & Shave', ratePercentage: 12 },
      { categoryName: 'Beard Spa', ratePercentage: 15 },
    ],
    todaySales: 3890,
    monthlySales: 128000,
    commissionEarnedToday: 466,
    commissionEarnedMonth: 15360,
    tipsToday: 410,
    rating: 4.9,
    completedAppointmentsCount: 5,
    shifts: [
      { day: 'Mon', shiftType: 'Off', startTime: '-', endTime: '-' },
      { day: 'Tue', shiftType: 'Morning', startTime: '09:00 AM', endTime: '04:00 PM' },
      { day: 'Wed', shiftType: 'Full Day', startTime: '09:30 AM', endTime: '07:30 PM' },
      { day: 'Thu', shiftType: 'Full Day', startTime: '09:30 AM', endTime: '07:30 PM' },
      { day: 'Fri', shiftType: 'Full Day', startTime: '09:30 AM', endTime: '08:00 PM' },
      { day: 'Sat', shiftType: 'Full Day', startTime: '09:00 AM', endTime: '08:30 PM' },
      { day: 'Sun', shiftType: 'Full Day', startTime: '10:00 AM', endTime: '07:00 PM' },
    ],
    emergencyContact: {
      name: 'Pooja Verma',
      relationship: 'Sister',
      phone: '+91 99887 00011',
    },
    specialties: ['Royal Hot Towel Shave', 'Fade Haircuts', 'Beard Design', 'Head Massage'],
    bio: 'Precision barbering specialist focusing on modern gentleman grooming.',
    payoutStatus: 'Paid',
  },
  {
    id: 'emp-4',
    name: 'Ananya Deshmukh',
    roleTitle: 'Aesthetician & Makeup Artist',
    department: 'Skin & Aesthetics',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    email: 'ananya.d@beigesalon.com',
    phone: '+91 97654 32109',
    startDate: '10 Nov 2023',
    status: 'On Shift',
    baseSalary: 35000,
    commissionRate: 12,
    commissionTiers: [
      { categoryName: 'Facials & Peelings', ratePercentage: 14 },
      { categoryName: 'Bridal & Party Makeup', ratePercentage: 15 },
    ],
    todaySales: 2200,
    monthlySales: 98000,
    commissionEarnedToday: 264,
    commissionEarnedMonth: 11760,
    tipsToday: 200,
    rating: 4.7,
    completedAppointmentsCount: 4,
    shifts: DEFAULT_WEEKLY_SHIFTS,
    emergencyContact: {
      name: 'Vikram Deshmukh',
      relationship: 'Brother',
      phone: '+91 97654 88899',
    },
    specialties: ['Hydra Facial', 'Gold Glow Skin Treatment', 'Airbrush Makeup', 'Pedicure Spa'],
    bio: 'Licensed aesthetician specializing in clinical skincare rejuvenations.',
    payoutStatus: 'Paid',
  },
  {
    id: 'emp-5',
    name: 'Karan Malhotra',
    roleTitle: 'Hair Specialist',
    department: 'Hair Care',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    email: 'karan.malhotra@beigesalon.com',
    phone: '+91 98220 11223',
    startDate: '01 Jun 2024',
    status: 'Off Duty',
    baseSalary: 28000,
    commissionRate: 10,
    todaySales: 1800,
    monthlySales: 74000,
    commissionEarnedToday: 180,
    commissionEarnedMonth: 7400,
    tipsToday: 150,
    rating: 4.6,
    completedAppointmentsCount: 4,
    shifts: [
      { day: 'Mon', shiftType: 'Evening', startTime: '01:00 PM', endTime: '08:00 PM' },
      { day: 'Tue', shiftType: 'Evening', startTime: '01:00 PM', endTime: '08:00 PM' },
      { day: 'Wed', shiftType: 'Off', startTime: '-', endTime: '-' },
      { day: 'Thu', shiftType: 'Morning', startTime: '09:00 AM', endTime: '04:00 PM' },
      { day: 'Fri', shiftType: 'Evening', startTime: '01:00 PM', endTime: '08:00 PM' },
      { day: 'Sat', shiftType: 'Full Day', startTime: '09:00 AM', endTime: '08:00 PM' },
      { day: 'Sun', shiftType: 'Full Day', startTime: '10:00 AM', endTime: '06:00 PM' },
    ],
    emergencyContact: {
      name: 'Anita Malhotra',
      relationship: 'Mother',
      phone: '+91 98220 55443',
    },
    specialties: ['Scalp Treatments', 'Men Styling', 'Color Touchups', 'Hair Wash & Spa'],
    bio: 'Energetic hair artist passionate about modern urban hair trends.',
    payoutStatus: 'Pending',
  },
  {
    id: 'emp-6',
    name: 'Sunita Nambiar',
    roleTitle: 'Salon Manager',
    department: 'Management',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    email: 'sunita.nambiar@beigesalon.com',
    phone: '+91 98990 11223',
    startDate: '01 Jan 2021',
    status: 'On Shift',
    baseSalary: 60000,
    commissionRate: 18,
    todaySales: 0,
    monthlySales: 0,
    commissionEarnedToday: 0,
    commissionEarnedMonth: 0,
    tipsToday: 0,
    rating: 5.0,
    completedAppointmentsCount: 0,
    shifts: [
      { day: 'Mon', shiftType: 'Full Day', startTime: '08:30 AM', endTime: '06:30 PM' },
      { day: 'Tue', shiftType: 'Full Day', startTime: '08:30 AM', endTime: '06:30 PM' },
      { day: 'Wed', shiftType: 'Full Day', startTime: '08:30 AM', endTime: '06:30 PM' },
      { day: 'Thu', shiftType: 'Full Day', startTime: '08:30 AM', endTime: '06:30 PM' },
      { day: 'Fri', shiftType: 'Full Day', startTime: '08:30 AM', endTime: '06:30 PM' },
      { day: 'Sat', shiftType: 'Morning', startTime: '08:30 AM', endTime: '02:00 PM' },
      { day: 'Sun', shiftType: 'Off', startTime: '-', endTime: '-' },
    ],
    emergencyContact: {
      name: 'Gopal Nambiar',
      relationship: 'Spouse',
      phone: '+91 98990 88776',
    },
    specialties: ['Operations Management', 'Inventory Control', 'Client Experience', 'Staff Training'],
    bio: '12+ years experience managing high-end boutique luxury salons and spas.',
    payoutStatus: 'Paid',
  },
  {
    id: 'emp-7',
    name: 'Priya Sundaram',
    roleTitle: 'Front Desk Executive',
    department: 'Front Desk',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    email: 'priya.sundaram@beigesalon.com',
    phone: '+91 98450 66778',
    startDate: '15 Sep 2023',
    status: 'On Shift',
    baseSalary: 26000,
    commissionRate: 5,
    todaySales: 1200,
    monthlySales: 34000,
    commissionEarnedToday: 60,
    commissionEarnedMonth: 1700,
    tipsToday: 100,
    rating: 4.9,
    completedAppointmentsCount: 0,
    shifts: DEFAULT_WEEKLY_SHIFTS,
    emergencyContact: {
      name: 'Suresh Sundaram',
      relationship: 'Father',
      phone: '+91 98450 11223',
    },
    specialties: ['POS Billing', 'Client Concierge', 'Appointment Scheduling', 'Voucher & Gift Cards'],
    bio: 'Customer hospitality enthusiast ensuring flawless check-in and checkout experiences.',
    payoutStatus: 'Paid',
  },
  {
    id: 'emp-8',
    name: 'Vikram Roy',
    roleTitle: 'Hair Specialist',
    department: 'Hair Care',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=250',
    email: 'vikram.roy@beigesalon.com',
    phone: '+91 97112 33445',
    startDate: '10 Feb 2025',
    status: 'On Leave',
    baseSalary: 24000,
    commissionRate: 10,
    todaySales: 0,
    monthlySales: 45000,
    commissionEarnedToday: 0,
    commissionEarnedMonth: 4500,
    tipsToday: 0,
    rating: 4.5,
    completedAppointmentsCount: 0,
    shifts: DEFAULT_WEEKLY_SHIFTS,
    emergencyContact: {
      name: 'Maya Roy',
      relationship: 'Spouse',
      phone: '+91 97112 88990',
    },
    specialties: ['Blowouts', 'Scalp Spa', 'Junior Styling', 'Hair Washing'],
    bio: 'Promising junior stylist eager to learn advanced hair coloring and texture work.',
    payoutStatus: 'Pending',
  },
];
