import { ExpenseItem } from '../types/expense';

export const INITIAL_EXPENSES: ExpenseItem[] = [
  {
    id: 'EXP-101',
    title: 'Monthly Salon Premises Rent (August)',
    category: 'Utilities & Rent',
    amount: 125000,
    date: '2026-08-01',
    paymentMethod: 'Bank Transfer',
    paidTo: 'Apex Commercial Properties',
    approvedBy: 'Meera Rajput (Owner)',
    status: 'Approved',
    notes: 'Paid via RTGS for Bandra West Salon Branch.',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'EXP-102',
    title: 'Loreal Professional Shampoo Bulk Replenishment',
    category: 'Salon Supplies',
    amount: 38400,
    date: '2026-08-03',
    paymentMethod: 'UPI / GPay',
    paidTo: 'Beauty Care Wholesalers Mumbai',
    approvedBy: 'Karan Sharma (Manager)',
    status: 'Approved',
    notes: '12x 1500ml Vitamin Color Shampoo & Masks.',
    receiptUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'EXP-103',
    title: 'Electricity Bill (BEST Mumbai AC & Lighting)',
    category: 'Utilities & Rent',
    amount: 28650,
    date: '2026-08-04',
    paymentMethod: 'Bank Transfer',
    paidTo: 'BEST Undertaking Electricity',
    approvedBy: 'Karan Sharma (Manager)',
    status: 'Approved',
    notes: 'Meter ID #89230491 - July AC heavy usage.',
  },
  {
    id: 'EXP-104',
    title: 'Staff Daily Tea, Coffee & Gourmet Snacks Supply',
    category: 'Staff Welfare & Refreshments',
    amount: 6200,
    date: '2026-08-05',
    paymentMethod: 'Cash',
    paidTo: 'Royal Caterers & Pantry',
    approvedBy: 'Front Desk Lead',
    status: 'Approved',
    notes: 'Pantry restocking for salon staff & client espresso bar.',
  },
  {
    id: 'EXP-105',
    title: 'Hydraulic Styling Chair Oil Leakage Repair',
    category: 'Maintenance & Repairs',
    amount: 4500,
    date: '2026-08-06',
    paymentMethod: 'UPI / GPay',
    paidTo: 'Precision Salon Fitters',
    approvedBy: 'Karan Sharma (Manager)',
    status: 'Pending Approval',
    notes: 'Station #3 hydraulic pump seal replacement.',
  },
  {
    id: 'EXP-106',
    title: 'Instagram & Facebook Ads - Monsoon Festive Offer',
    category: 'Marketing & Ads',
    amount: 15000,
    date: '2026-08-06',
    paymentMethod: 'Credit Card',
    paidTo: 'Meta Ads Manager India',
    approvedBy: 'Meera Rajput (Owner)',
    status: 'Approved',
    notes: 'Targeted ad campaign for Keratin treatment package.',
  },
  {
    id: 'EXP-107',
    title: 'High-Speed Fiber Internet & Landline Bill',
    category: 'Utilities & Rent',
    amount: 2999,
    date: '2026-08-07',
    paymentMethod: 'UPI / GPay',
    paidTo: 'Airtel Broadband Ltd',
    approvedBy: 'Karan Sharma (Manager)',
    status: 'Approved',
    notes: '300 Mbps Dedicated Line for POS & Guest Wi-Fi.',
  },
  {
    id: 'EXP-108',
    title: 'Sterilizer Machine UV Bulb & Towel Warmer Service',
    category: 'Maintenance & Repairs',
    amount: 3200,
    date: '2026-08-07',
    paymentMethod: 'Cash',
    paidTo: 'CleanCare Equipment Service',
    approvedBy: 'Pending Manager',
    status: 'Pending Approval',
    notes: 'Replaced 2 UV germicidal tubes in facial room.',
  },
];
