import { SalonService } from '../types/service';

export const INITIAL_SERVICES: SalonService[] = [
  {
    id: 'srv-1',
    code: 'HC-101',
    name: 'Precision Hair Cut & Styling',
    category: 'Hair Care & Cut',
    genderTarget: 'Unisex',
    basePrice: 850,
    durationMinutes: 45,
    memberDiscountPercent: 15,
    description: 'Custom scalp consultation, hair wash, precision shear haircut, and blow-dry styling with heat protectant.',
    requiredConsumables: [
      { itemName: 'Argan Oil Smoothing Serum 100ml', qtyPerSession: '2 pumps' },
      { itemName: 'Disposable Towels (Pack of 100)', qtyPerSession: '1 towel' },
    ],
    recommendedStylistRole: 'Master Senior Stylist',
    status: 'Active',
    isPopular: true,
    totalBookings: 148,
    totalRevenue: 125800,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-2',
    code: 'HC-102',
    name: 'Keratin Deep Nourishing Spa',
    category: 'Hair Care & Cut',
    genderTarget: 'Unisex',
    basePrice: 2800,
    durationMinutes: 75,
    memberDiscountPercent: 15,
    description: 'Intense keratin infusion treatment with ozone steam, head pressure point massage, and shine polish.',
    requiredConsumables: [
      { itemName: 'Keratin Nourishing Shampoo 1000ml', qtyPerSession: '30ml' },
      { itemName: 'Argan Oil Smoothing Serum 100ml', qtyPerSession: '3 pumps' },
    ],
    recommendedStylistRole: 'Senior Colorist & Spa Expert',
    status: 'Active',
    isPopular: true,
    totalBookings: 92,
    totalRevenue: 257600,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-3',
    code: 'HC-103',
    name: 'Balayage & Full Hair Color',
    category: 'Hair Care & Cut',
    genderTarget: 'Female',
    basePrice: 4500,
    durationMinutes: 120,
    memberDiscountPercent: 20,
    description: 'Hand-painted dimensional highlights with ammonia-free colors, Plex bonder, and gloss toner treatment.',
    requiredConsumables: [
      { itemName: 'Bleach Powder Blue 500g', qtyPerSession: '60g' },
      { itemName: 'Hair Color Black No. 1 (L’Oréal)', qtyPerSession: '1 tube' },
    ],
    recommendedStylistRole: 'Senior Colorist & Spa Expert',
    status: 'Active',
    isPopular: true,
    totalBookings: 64,
    totalRevenue: 288000,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-4',
    code: 'SK-201',
    name: 'Hydra Glow Deep Cleansing Facial',
    category: 'Skin & Facials',
    genderTarget: 'Unisex',
    basePrice: 2500,
    durationMinutes: 60,
    memberDiscountPercent: 15,
    description: '6-step medical grade hydra-dermabrasion exfoliation, extraction, LED light therapy, and hyaluronic acid mask.',
    requiredConsumables: [
      { itemName: 'Hydra Facial Serum Set (A+B)', qtyPerSession: '1 vial' },
      { itemName: 'Facial Cleansing Sponges (50s)', qtyPerSession: '2 sponges' },
    ],
    recommendedStylistRole: 'Aesthetician & Makeup Artist',
    status: 'Active',
    isPopular: true,
    totalBookings: 110,
    totalRevenue: 275000,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-5',
    code: 'SK-202',
    name: '24K Gold Radiance Facial',
    category: 'Skin & Facials',
    genderTarget: 'Unisex',
    basePrice: 3200,
    durationMinutes: 75,
    memberDiscountPercent: 15,
    description: 'Luxury gold foil infusion facial designed for instant skin firming, collagen boost, and bridal glow.',
    requiredConsumables: [
      { itemName: 'Facial Cleansing Sponges (50s)', qtyPerSession: '2 sponges' },
    ],
    recommendedStylistRole: 'Aesthetician & Makeup Artist',
    status: 'Active',
    isPopular: false,
    totalBookings: 42,
    totalRevenue: 134400,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1512290900673-700242211593?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-6',
    code: 'GB-301',
    name: 'Royal Executive Beard Sculpting',
    category: 'Beard & Grooming',
    genderTarget: 'Male',
    basePrice: 650,
    durationMinutes: 30,
    memberDiscountPercent: 10,
    description: 'Hot towel wrap, razor edge lining, organic beard oil treatment, and aromatic aftershave tonic.',
    requiredConsumables: [
      { itemName: 'Styling Gel Ultra Hold 500ml', qtyPerSession: '10ml' },
      { itemName: 'Disposable Towels (Pack of 100)', qtyPerSession: '1 towel' },
    ],
    recommendedStylistRole: 'Grooming & Barber Lead',
    status: 'Active',
    isPopular: true,
    totalBookings: 125,
    totalRevenue: 81250,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-7',
    code: 'GB-302',
    name: 'Gentleman Grooming Combo (Cut + Shave + Detan)',
    category: 'Beard & Grooming',
    genderTarget: 'Male',
    basePrice: 1500,
    durationMinutes: 60,
    memberDiscountPercent: 15,
    description: 'Complete makeover including executive haircut, charcoal facial detan pack, and sharp beard grooming.',
    requiredConsumables: [
      { itemName: 'Styling Gel Ultra Hold 500ml', qtyPerSession: '15ml' },
    ],
    recommendedStylistRole: 'Grooming & Barber Lead',
    status: 'Active',
    isPopular: true,
    totalBookings: 88,
    totalRevenue: 132000,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-8',
    code: 'NL-401',
    name: 'Lavender Spa Pedicure & Polish',
    category: 'Nails & Beauty',
    genderTarget: 'Unisex',
    basePrice: 1200,
    durationMinutes: 50,
    memberDiscountPercent: 15,
    description: 'Exfoliating Dead Sea salt scrub, callus reduction, warm paraffin wax dip, and precision nail polish.',
    requiredConsumables: [
      { itemName: 'Pedicure Salt Scrub Lavender 1kg', qtyPerSession: '50g' },
    ],
    recommendedStylistRole: 'Aesthetician & Makeup Artist',
    status: 'Active',
    isPopular: false,
    totalBookings: 76,
    totalRevenue: 91200,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-9',
    code: 'SP-501',
    name: 'Aroma De-Stress Back & Shoulder Massage',
    category: 'Spa & Relaxation',
    genderTarget: 'Unisex',
    basePrice: 1800,
    durationMinutes: 45,
    memberDiscountPercent: 15,
    description: 'Therapeutic pressure massage using lavender essential oils to relieve deep muscular tightness.',
    requiredConsumables: [
      { itemName: 'Disposable Towels (Pack of 100)', qtyPerSession: '2 towels' },
    ],
    recommendedStylistRole: 'Senior Colorist & Spa Expert',
    status: 'Active',
    isPopular: false,
    totalBookings: 53,
    totalRevenue: 95400,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-10',
    code: 'MB-601',
    name: 'HD Airbrush Bridal Makeup & Styling',
    category: 'Makeup & Bridal',
    genderTarget: 'Female',
    basePrice: 12000,
    durationMinutes: 180,
    memberDiscountPercent: 10,
    description: 'Full bridal makeover including airbrush base, saree/lehenga draping, hair ornamentation, and lash extensions.',
    requiredConsumables: [
      { itemName: 'Facial Cleansing Sponges (50s)', qtyPerSession: '4 sponges' },
    ],
    recommendedStylistRole: 'Aesthetician & Makeup Artist',
    status: 'Active',
    isPopular: true,
    totalBookings: 24,
    totalRevenue: 288000,
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=500',
  },
  {
    id: 'srv-11',
    code: 'CP-701',
    name: 'Beige Signature Weekend Makeover Package',
    category: 'Combo Packages',
    genderTarget: 'Unisex',
    basePrice: 3800,
    durationMinutes: 120,
    memberDiscountPercent: 20,
    description: 'Includes Haircut, Keratin Express Spa, Hydra Facial Light, and Foot Reflexology session.',
    requiredConsumables: [
      { itemName: 'Keratin Nourishing Shampoo 1000ml', qtyPerSession: '20ml' },
      { itemName: 'Facial Cleansing Sponges (50s)', qtyPerSession: '2 sponges' },
    ],
    recommendedStylistRole: 'Master Senior Stylist',
    status: 'Active',
    isPopular: true,
    totalBookings: 80,
    totalRevenue: 304000,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&q=80&w=500',
  },
];
